// Starter rind.policy.yaml generator (D-040 Phase A5).
//
// Pure function — returns a YAML string, does no file I/O.
// The init CLI writes the result to disk.
//
// The generated file is designed to be immediately useful:
//   - Enables cli-protection pack out of the box (safe default)
//   - Provides commented-out examples for common patterns
//   - Links to docs for further customisation

// ─── Generator ────────────────────────────────────────────────────────────────

/**
 * Returns a starter rind.policy.yaml string.
 * The policy is ready to use — cli-protection is enabled so destructive CLI
 * commands are blocked immediately. All other packs and custom rules are
 * documented as commented-out examples.
 */
export function generateStarterPolicyYaml(): string {
  return `# rind.policy.yaml — generated by rind-proxy init
#
# This file controls what your AI agents are allowed to do.
# Rind evaluates every tool call against these rules before forwarding it.
#
# Docs: https://rind.sh/docs/policy
# Rule reference: https://rind.sh/docs/policy/rules

# ── Policy packs ──────────────────────────────────────────────────────────────
#
# Packs are curated rule sets maintained by Rind. Enable the ones you need.
# Available packs: cli-protection, data-exfiltration, secrets-protection,
#                  billing-protection, infra-protection
#
packs:
  # Blocks dangerous CLI commands: rm -rf, npm publish, gh repo delete,
  # aws ec2 terminate-instances, kubectl delete, curl data exfiltration, etc.
  # Requires approval for cloud-destructive operations.
  - cli-protection

  # Uncomment to enable additional packs:
  # - data-exfiltration    # Blocks data exfil via curl, wget, netcat
  # - secrets-protection   # Blocks reading .env, ~/.ssh/*, AWS credentials
  # - infra-protection     # Blocks DNS/firewall changes, kernel parameters

# ── Custom rules ──────────────────────────────────────────────────────────────
#
# Custom rules let you extend beyond the built-in packs.
# Rules are evaluated in priority order (lower number = evaluated first).
# First matching rule wins.
#
# Rule actions:
#   allow             — permit the tool call (use to override pack denials)
#   deny              — block with an error message
#   require-approval  — pause and ask a human before proceeding
#   rate-limit        — allow but cap calls per time window
#
policies:
  # Example: block writes to production config files
  # - name: no-production-config-writes
  #   description: "Prevent agents from modifying production configuration"
  #   priority: 10
  #   tool: Write
  #   parameters:
  #     file_path:
  #       regex: ".*\\\\.prod\\\\.(yaml|json|env)$"
  #   action: deny
  #   reason: "Production config files must be changed via CI/CD, not by agents"

  # Example: require approval before any database schema change
  # - name: db-schema-approval
  #   description: "Require human approval for all schema migrations"
  #   priority: 20
  #   tool: Bash
  #   parameters:
  #     command:
  #       regex: "(supabase|prisma|flyway|alembic).*(migrate|push|reset)"
  #   action: require-approval
  #   reason: "Database schema changes require human review"

  # Example: rate-limit expensive LLM API calls
  # - name: llm-api-rate-limit
  #   description: "Limit agent-initiated LLM API calls to 20 per hour"
  #   priority: 30
  #   tool: WebFetch
  #   parameters:
  #     url:
  #       regex: "(api\\.openai\\.com|api\\.anthropic\\.com)"
  #   action: rate-limit
  #   rateLimit:
  #     maxCalls: 20
  #     windowSeconds: 3600
`;
}
