// LLM API proxy gateway — Hono sub-app factory.
//
// Responsibility: mount /llm/:provider/* routes, orchestrate the LLM proxy pipeline:
//   1. Parse + validate inbound request
//   2. Pre-forward policy check (evaluateLlm)
//   3. Forward to upstream (streaming or non-streaming)
//   4. Emit llm:request + llm:response events
//   5. Post-stream async scanning (wired in Phase 7)
//
// Follows the same factory pattern as mcpGateway() in transport/gateway.ts.
// All business logic is in pure functions; this file handles HTTP concerns only.

import { Hono, type Context } from 'hono';
import { stream } from 'hono/streaming';
import { createHash, randomUUID } from 'node:crypto';
import { RateLimiter } from '../../rate-limiter.js';
import type pino from 'pino';
import type { RindEventBus } from '../../event-bus.js';
import type { PolicyEngine } from '../../policy/engine.js';
import type { LlmCallEvent, LlmProxyConfig } from './types.js';
import { anthropicProvider } from './providers/anthropic.js';
import { openaiProvider } from './providers/openai.js';
import type { LlmProxyProvider } from './providers/interface.js';
import { ProviderParseError } from './providers/interface.js';
import { forwardLlmRequest } from './forward.js';
import type { ForwardLlmOptions } from './forward.js';
import { createAnthropicAccumulator, createOpenAIAccumulator } from './streaming.js';
import { scanLlmRequest } from './request-scanner.js';
import { scanLlmResponse } from './response-scanner.js';
import { calculateCost } from './cost-calculator.js';
import { evaluateLlmContent, applyPseudonymizeToBody } from './content-policy.js';
import { evaluateLlmResponseContent, patchResponseBodyWithRedaction, rehydrateResponseBody } from './content-policy-response.js';
import type { PIIVault } from '../../pii-vault.js';
import type { LlmForwardFn, ProxyConfig } from '../../types.js';
import type { ISessionStore } from '../../session.js';

// ─── Gateway options ──────────────────────────────────────────────────────────

export interface LlmGatewayOptions {
  config: LlmProxyConfig;
  bus: RindEventBus;
  policyEngine: PolicyEngine;
  logger: pino.Logger;
  /**
   * Optional post-response scan hook. Called async after the response completes.
   * Does not block the response — fire and forget.
   */
  onResponseComplete?: (event: LlmCallEvent) => void;
  /**
   * Injectable forward function — replaces the real HTTP forwarding.
   * Used in simulation scenarios and tests to inject canned LLM responses
   * without making real network calls.
   */
  forwardFn?: LlmForwardFn;
  /** Per-layer detection mode overrides. Default for all layers: 'block'. */
  layers?: ProxyConfig['layers'];
  /**
   * Session store — used to retrieve the credential vault for the current session.
   * When provided, credentials in tool_results and LLM responses are pseudonymized
   * with the session-scoped vault (consistent synthetics with the MCP proxy path).
   * Optional for backward compatibility; when absent a per-call temporary vault is used.
   */
  sessionStore?: ISessionStore;
}

// ─── Conversation tracker ─────────────────────────────────────────────────────
//
// Tracks the tool_use_id → LLM call linkage so consecutive turns in a conversation
// can be chained: LlmCall N (generates tool_uses) → tool execution → LlmCall N+1
// (sends tool_results referencing those ids → parentLlmCallId = N.id).
//
// Entries are evicted after 30 minutes (well beyond any realistic conversation turn).

interface ToolUseEntry {
  llmCallId: string;
  conversationId: string;
  expiresAt: number;
}

class ConversationTracker {
  private readonly toolUseMap = new Map<string, ToolUseEntry>();

  /** Register tool_use blocks generated by a completed LLM response. */
  register(toolUseIds: string[], llmCallId: string, conversationId: string): void {
    const expiresAt = Date.now() + 30 * 60_000;
    for (const id of toolUseIds) {
      this.toolUseMap.set(id, { llmCallId, conversationId, expiresAt });
    }
    this.evict();
  }

  /**
   * Look up the parent LLM call for a set of tool_use_ids referenced in a request.
   * Returns the first match found (all ids in a turn share the same parent call).
   * Also evicts expired entries so pure text-only conversations (no tool calls)
   * don't accumulate stale entries indefinitely.
   */
  resolve(toolUseIds: string[]): { llmCallId?: string; conversationId?: string } {
    this.evict();
    const now = Date.now();
    for (const id of toolUseIds) {
      const entry = this.toolUseMap.get(id);
      if (entry && entry.expiresAt > now) {
        return { llmCallId: entry.llmCallId, conversationId: entry.conversationId };
      }
    }
    return {};
  }

  private evict(): void {
    const now = Date.now();
    for (const [key, entry] of this.toolUseMap.entries()) {
      if (entry.expiresAt <= now) this.toolUseMap.delete(key);
    }
  }
}

// ─── Accumulator factory map ──────────────────────────────────────────────────

const ACCUMULATOR_FACTORIES: Record<string, typeof createAnthropicAccumulator> = {
  anthropic: createAnthropicAccumulator,
  openai: createOpenAIAccumulator,
};

// ─── Session correlation via API key hash ─────────────────────────────────────

/**
 * Derive a stable session ID from the API key.
 * This lets us correlate LLM calls with tool calls in the same Claude Code session
 * without storing the actual key.
 */
function deriveSessionId(headers: Record<string, string>): string {
  // Explicit session ID (e.g. passed by simulation runner or Claude Code hook) takes precedence
  const explicit = headers['x-rind-session-id'];
  if (explicit) return explicit;
  const key =
    headers['x-api-key'] ??
    headers['authorization']?.replace(/^Bearer\s+/i, '') ??
    '';
  if (!key) return 'unknown-session';
  return createHash('sha256').update(key).digest('hex').slice(0, 16);
}

// ─── Build LlmCallEvent from request ─────────────────────────────────────────

function buildInitialEvent(
  provider: LlmProxyProvider,
  headers: Record<string, string>,
  body: unknown,
  config: LlmProxyConfig,
  tracker: ConversationTracker,
): LlmCallEvent {
  const meta = provider.parseRequest(body, config.logLevel);
  const id = randomUUID();

  // Resolve conversation thread via tool_use_id chain
  const { llmCallId: parentLlmCallId, conversationId: parentConversationId } =
    meta.referencedToolUseIds.length > 0
      ? tracker.resolve(meta.referencedToolUseIds)
      : {};

  return {
    id,
    sessionId: deriveSessionId(headers),
    agentId: headers['x-rind-agent-id'] ?? `llm-${provider.name}`,
    provider: provider.name,
    model: meta.model,
    timestamp: Date.now(),
    messageCount: meta.messageCount,
    systemPromptLength: meta.systemPromptLength,
    streaming: meta.isStreaming,
    messages: meta.messages,
    outcome: 'forwarded', // optimistic — updated to 'error' or 'blocked' if needed
    referencedToolUseIds: meta.referencedToolUseIds.length > 0 ? meta.referencedToolUseIds : undefined,
    parentLlmCallId,
    conversationId: parentConversationId ?? id, // root call: conversationId = its own id
  };
}

// ─── Handler factory ──────────────────────────────────────────────────────────

/**
 * Build a Hono handler for a given LLM provider.
 * Handles both streaming and non-streaming requests transparently.
 */
// ─── Shared response enrichment ───────────────────────────────────────────────
//
// Both streaming and non-streaming paths produce the same enriched LlmCallEvent.
// This closure captures the context needed so each path is a single call site.

interface EnrichedEventTiming {
  statusCode: number;
  durationMs?: number;
  ttfbMs?: number;
}

function makeEnricher(
  config: LlmGatewayOptions['config'],
  bus: LlmGatewayOptions['bus'],
  logger: LlmGatewayOptions['logger'],
  tracker: ConversationTracker,
  onResponseComplete: LlmGatewayOptions['onResponseComplete'],
  llmScannerMode: 'block' | 'alert' | 'off' = 'block',
) {
  return function emitEnrichedEvent(
    baseEvent: LlmCallEvent,
    meta: import('./providers/interface.js').LlmResponseMeta,
    timing: EnrichedEventTiming,
    vault?: PIIVault,
  ): void {
    // Rehydrate a local copy for threat scanning — detectors must see real values, not tokens.
    // The event itself stores the synthetic (pre-rehydration) text so original PII never
    // reaches the ring buffer, audit log, or dashboard.
    const rehydratedForScan = vault ? vault.rehydrate(meta.responseText ?? '') : (meta.responseText ?? '');
    const responseThreats = llmScannerMode !== 'off' ? scanLlmResponse(rehydratedForScan) : [];
    const inputTokens = meta.inputTokens > 0 ? meta.inputTokens : undefined;
    const outputTokens = meta.outputTokens > 0 ? meta.outputTokens : undefined;
    const { toolUses } = meta;
    const enrichedEvent: LlmCallEvent = {
      ...baseEvent,
      statusCode: timing.statusCode,
      totalDurationMs: timing.durationMs,
      ttfbMs: timing.ttfbMs,
      inputTokens,
      outputTokens,
      estimatedCostUsd: (inputTokens != null && outputTokens != null)
        ? calculateCost(baseEvent.model, inputTokens, outputTokens)
        : undefined,
      responseText: meta.responseText, // synthetic tokens — safe for audit log
      ...(toolUses && toolUses.length > 0 ? { toolUses } : {}),
      ...(responseThreats.length > 0 ? { responseThreats } : {}),
    };
    if (toolUses && toolUses.length > 0) {
      tracker.register(toolUses.map((t) => t.id), enrichedEvent.id, enrichedEvent.conversationId ?? enrichedEvent.id);
    }
    if (responseThreats.length > 0) {
      logger.warn({ model: baseEvent.model, threatCount: responseThreats.length }, 'LLM response threats detected');
    }
    vault?.dispose();
    bus.emit('llm:response', enrichedEvent);
    if (
      config.costAnomalyThresholdUsd != null &&
      enrichedEvent.estimatedCostUsd != null &&
      enrichedEvent.estimatedCostUsd > config.costAnomalyThresholdUsd
    ) {
      bus.emit('llm:cost-anomaly', { event: enrichedEvent, thresholdUsd: config.costAnomalyThresholdUsd });
      logger.warn(
        { model: baseEvent.model, cost: enrichedEvent.estimatedCostUsd, threshold: config.costAnomalyThresholdUsd },
        'LLM cost anomaly detected',
      );
    }
    onResponseComplete?.(enrichedEvent);
  };
}

// ─── Handler factory ──────────────────────────────────────────────────────────

function buildProviderHandler(provider: LlmProxyProvider, opts: LlmGatewayOptions, rateLimiter: RateLimiter, tracker: ConversationTracker) {
  const { config, bus, policyEngine, logger, onResponseComplete } = opts;
  // Note: for the LLM scanner, 'alert' and 'block' modes are functionally equivalent
  // because scanLlmRequest/scanLlmResponse are observation-only — they attach threats
  // to the LlmCallEvent but never block the request themselves. Blocking is handled by
  // content policy rules (DENY/REDACT actions) evaluated separately. Only 'off' has
  // a distinct effect: it skips scanning entirely (no threats recorded, no rules matched).
  const llmScannerMode = opts.layers?.['llm-scanner']?.mode ?? 'block';
  const emitEnrichedEvent = makeEnricher(config, bus, logger, tracker, onResponseComplete, llmScannerMode);

  return async (c: Context) => {
    // ── 1. Parse request body ────────────────────────────────────────────────
    let body: unknown;
    try {
      body = await c.req.json();
    } catch {
      return c.json({ error: { type: 'invalid_request', message: 'Request body must be valid JSON' } }, 400);
    }

    // ── 2. Build inbound headers map (lowercase keys) ────────────────────────
    const inboundHeaders: Record<string, string> = {};
    c.req.raw.headers.forEach((value, key) => {
      inboundHeaders[key.toLowerCase()] = value;
    });

    // ── 3. Parse request metadata + build initial event ──────────────────────
    let event: LlmCallEvent;
    try {
      event = buildInitialEvent(provider, inboundHeaders, body, config, tracker);
    } catch (err) {
      if (err instanceof ProviderParseError) {
        return c.json({ error: { type: 'invalid_request', message: err.message } }, 400);
      }
      throw err;
    }

    // ── 3a-ii. Session-scoped credential vault ───────────────────────────────
    // Retrieve (or lazily create) the vault for this session so that credentials
    // in tool_results and LLM responses are pseudonymized with the same RIND_SYNTH
    // synthetics as the MCP proxy path (same HMAC key + agentId → same tag).
    // Optional: if no sessionStore is configured, evaluateLlmContent/Response will
    // create a temporary per-call vault instead.
    const credVault = opts.sessionStore?.getCredentialVault(event.agentId, event.sessionId);

    // ── 3b. Request scanning (sync, pre-forward) ─────────────────────────────
    // Scan outbound prompt for credentials and PII. Attaches threats to the event
    // for audit/dashboard visibility. Does not block forwarding on its own — a
    // policy rule with llmModel/llmProvider + DENY action is the enforcement path.
    if (llmScannerMode !== 'off') {
      const requestThreats = scanLlmRequest(body);
      if (requestThreats.length > 0) {
        event = { ...event, requestThreats };
        logger.warn({ model: event.model, threatCount: requestThreats.length }, 'LLM request threats detected');
      }
    }

    // ── 3c. Content-based policy evaluation ──────────────────────────────────
    // Evaluates rules with match.content (PII, secrets, injection, DLP).
    // May block the request, pseudonymize, or redact the body before forwarding.
    const contentRules = policyEngine.getContentRules();
    const contentResult = await evaluateLlmContent(body, event, contentRules, credVault);

    if (contentResult.action === 'DENY') {
      const blockedEvent: LlmCallEvent = {
        ...event,
        outcome: 'blocked',
        matchedRule: contentResult.matchedRule,
        contentInspection: contentResult.inspection,
      };
      bus.emit('llm:blocked', { event: blockedEvent, reason: contentResult.reason ?? 'Content policy DENY' });
      logger.info({ model: event.model, rule: contentResult.matchedRule }, 'LLM call blocked by content policy');
      return c.json(
        { error: { type: 'policy_denied', message: contentResult.reason ?? 'Request blocked by policy' } },
        403,
      );
    }

    // Attach content inspection audit to event (no PII values)
    if (contentResult.inspection.detectorsRan.length > 0) {
      event = { ...event, contentInspection: contentResult.inspection };
    }

    // Use sanitized body for all downstream steps (may be mutated by PSEUDONYMIZE/REDACT)
    const forwardBody = contentResult.sanitizedBody;
    // Vault reference for rehydration — undefined when no pseudonymization occurred
    let activeVault: PIIVault | undefined = contentResult.vault;

    // ── Scrub original PII from the audit event ──────────────────────────────
    // event.messages was built from the raw inbound body before pseudonymization.
    // Replace original values with their synthetics so logs never contain real PII.
    // Only needed when a vault is active (pseudonymization was applied).
    if (activeVault && event.messages !== undefined) {
      event = { ...event, messages: applyPseudonymizeToBody(event.messages, activeVault) };
    }

    // ── 4. Pre-forward policy check ──────────────────────────────────────────
    const policyResult = policyEngine.evaluateLlm(event);
    if (policyResult.action === 'DENY') {
      const blockedEvent: LlmCallEvent = { ...event, outcome: 'blocked', matchedRule: policyResult.matchedRule?.name };
      bus.emit('llm:blocked', { event: blockedEvent, reason: policyResult.reason ?? 'Policy DENY' });
      logger.info({ model: event.model, rule: policyResult.matchedRule?.name }, 'LLM call blocked by policy');
      activeVault?.dispose();
      activeVault = undefined;
      return c.json(
        { error: { type: 'policy_denied', message: policyResult.reason ?? 'Request blocked by policy' } },
        403,
      );
    }

    // ── 4b. LLM rate limiting (per-agent, per-provider) ─────────────────────
    if (config.rateLimitPerAgentPerMinute != null) {
      const rlResult = rateLimiter.check(event.agentId, `llm:${provider.name}`, {
        limit: config.rateLimitPerAgentPerMinute,
        windowMs: 60_000,
        scope: 'per_tool',
      });
      if (!rlResult.allowed) {
        const blockedEvent: LlmCallEvent = {
          ...event,
          outcome: 'blocked',
          errorMessage: `Rate limit exceeded: ${config.rateLimitPerAgentPerMinute} LLM calls/min`,
        };
        bus.emit('llm:blocked', { event: blockedEvent, reason: 'Rate limit exceeded' });
        activeVault?.dispose();
        activeVault = undefined;
        return c.json(
          { error: { type: 'rate_limit_exceeded', message: 'Too many LLM requests — slow down' } },
          429,
        );
      }
    }

    // Emit request event (outcome = 'forwarded' optimistically)
    bus.emit('llm:request', event);

    // ── 5. Forward to upstream ────────────────────────────────────────────────
    const upstreamBaseUrl =
      provider.name === 'anthropic' ? config.anthropicUpstream
      : provider.name === 'openai' ? config.openaiUpstream
      : config.googleUpstream;

    const inboundPath = c.req.path; // e.g. /llm/anthropic/v1/messages
    const forwardStart = Date.now();

    const forward = opts.forwardFn ?? forwardLlmRequest;
    const result = await forward(inboundPath, inboundHeaders, forwardBody, {
      provider,
      upstreamBaseUrl,
      logLevel: config.logLevel,
      createAccumulator: () => ACCUMULATOR_FACTORIES[provider.name]?.(config.logLevel) ?? createAnthropicAccumulator(config.logLevel),
    });

    // ── 6. Handle error from forwarding ─────────────────────────────────────
    // Cover both 4xx (401 invalid key, 429 rate-limited) and 5xx (upstream down).
    // Streaming errors (connection failures) are already caught above as 502/504.
    if (!result.stream && result.statusCode >= 400) {
      const errorEvent: LlmCallEvent = {
        ...event,
        outcome: 'error',
        statusCode: result.statusCode,
        errorMessage: (result.responseBody as Record<string, unknown> | undefined)?.['error']
          ? JSON.stringify((result.responseBody as Record<string, unknown>)['error'])
          : `Upstream returned ${result.statusCode}`,
        totalDurationMs: result.durationMs,
        ttfbMs: result.ttfbMs,
      };
      bus.emit('llm:response', errorEvent);
      activeVault?.dispose();
      activeVault = undefined;
      return new Response(JSON.stringify(result.responseBody), {
        status: result.statusCode,
        headers: { 'content-type': 'application/json' },
      });
    }

    // Forward upstream headers to client (status, content-type, etc.)
    for (const [key, value] of Object.entries(result.upstreamHeaders)) {
      c.header(key, value);
    }

    // ── 7a. Non-streaming response ───────────────────────────────────────────
    if (!result.stream) {
      if (result.meta) {
        // ── 7a-i. Response-side content policy ──────────────────────────────
        // Evaluated after the upstream responds but before returning to client.
        // DENY blocks the response body; REDACT pseudonymizes credentials in
        // assistant text (RIND_SYNTH synthetics, not [REDACTED]).
        const responseContentResult = await evaluateLlmResponseContent(
          result.meta.responseText ?? '',
          event,
          contentRules,
          credVault,
        );

        if (responseContentResult.action === 'DENY') {
          const blockedEvent: LlmCallEvent = {
            ...event,
            outcome: 'blocked',
            matchedRule: responseContentResult.matchedRule,
          };
          bus.emit('llm:blocked', { event: blockedEvent, reason: responseContentResult.reason ?? 'Response content policy DENY' });
          logger.info({ model: event.model, rule: responseContentResult.matchedRule }, 'LLM response blocked by content policy');
          activeVault?.dispose();
          activeVault = undefined;
          return c.json(
            { error: { type: 'policy_denied', message: responseContentResult.reason ?? 'Response blocked by policy' } },
            403,
          );
        }

        const finalMeta = responseContentResult.action === 'REDACT' && responseContentResult.redactedText
          ? { ...result.meta, responseText: responseContentResult.redactedText }
          : result.meta;

        // REDACT takes precedence: pseudonymize credentials in the response body before
        // returning to client (uses the pseudonymized text from evaluateLlmResponseContent).
        // Otherwise rehydrate vault tokens → original PII values before sending to client.
        // Must happen before emitEnrichedEvent disposes the vault.
        let finalBody: unknown = responseContentResult.action === 'REDACT'
          ? patchResponseBodyWithRedaction(result.responseBody, responseContentResult.redactedText)
          : result.responseBody;
        if (activeVault && responseContentResult.action !== 'REDACT') {
          finalBody = rehydrateResponseBody(finalBody, activeVault);
        }

        emitEnrichedEvent(event, finalMeta, { statusCode: result.statusCode, durationMs: result.durationMs, ttfbMs: result.ttfbMs }, activeVault);
        activeVault = undefined; // vault disposed inside emitEnrichedEvent
        return new Response(JSON.stringify(finalBody), {
          status: result.statusCode,
          headers: { 'content-type': 'application/json' },
        });
      } else {
        // No parsed meta (e.g. unexpected upstream format) — dispose vault to prevent leak
        activeVault?.dispose();
        activeVault = undefined;
      }
      return new Response(JSON.stringify(result.responseBody), {
        status: result.statusCode,
        headers: { 'content-type': 'application/json' },
      });
    }

    // ── 7b. Streaming response ───────────────────────────────────────────────
    const capturedEvent = event;
    const capturedTtfb = result.ttfbMs;
    const capturedForwardStart = forwardStart;
    const capturedStatusCode = result.statusCode;
    const capturedVault = activeVault;
    const capturedContentRules = contentRules; // capture for async response-side eval
    const capturedCredVault = credVault; // capture for async response-side credential pseudonymization
    activeVault = undefined; // ownership transferred to stream closure

    // ── 7b-i. Vault active: hold-back window rehydration ────────────────────
    // When PSEUDONYMIZE was applied to the request, tokens like <EMAIL_1> must
    // be replaced before bytes reach the client. We use a hold-back window of
    // maxTokenLength bytes: rehydrate and forward all bytes except the final
    // window; the window is prepended to the next chunk so no token can span a
    // send boundary. Only the window is ever held in memory — not the full stream.
    if (capturedVault) {
      const holdBack = capturedVault.maxTokenLength;
      const decoder = new TextDecoder();
      const encoder = new TextEncoder();

      return stream(c, async (s) => {
        let pending = '';
        const reader = result.stream!.getReader();
        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            pending += decoder.decode(value, { stream: true });
            if (pending.length > holdBack) {
              const cutAt = pending.length - holdBack;
              await s.write(encoder.encode(capturedVault.rehydrate(pending.slice(0, cutAt))));
              pending = pending.slice(cutAt);
            }
          }
          pending += decoder.decode(); // flush multi-byte codepoints at stream end
        } catch {
          result.stream!.cancel().catch(() => {});
        } finally {
          reader.releaseLock();
        }

        if (pending) {
          await s.write(encoder.encode(capturedVault.rehydrate(pending)));
        }

        // streamMeta has settled — stream was fully consumed above.
        // If streamMeta rejects (e.g. upstream error mid-stream), emit an error event
        // and dispose the vault; never leave the vault alive after request completion.
        let meta: import('./providers/interface.js').LlmResponseMeta;
        try {
          meta = (await result.streamMeta) ?? { model: capturedEvent.model, inputTokens: 0, outputTokens: 0 };
        } catch (err: unknown) {
          logger.error({ err, eventId: capturedEvent.id }, 'Failed to emit LLM stream response event');
          bus.emit('llm:response', {
            ...capturedEvent,
            outcome: 'error',
            errorMessage: err instanceof Error ? err.message : 'Stream pipeline error',
            ttfbMs: capturedTtfb,
            totalDurationMs: Date.now() - capturedForwardStart,
          });
          capturedVault.dispose();
          return;
        }

        const responseContentResult = await evaluateLlmResponseContent(
          meta.responseText ?? '',
          capturedEvent,
          capturedContentRules,
          capturedCredVault,
        );
        const isViolation = responseContentResult.action !== 'ALLOW';
        const vaultMeta: typeof meta = isViolation && responseContentResult.redactedText
          ? { ...meta, responseText: responseContentResult.redactedText }
          : meta;
        emitEnrichedEvent(
          isViolation ? { ...capturedEvent, outcome: 'policy-violation' } : capturedEvent,
          vaultMeta,
          { statusCode: capturedStatusCode, durationMs: Date.now() - capturedForwardStart, ttfbMs: capturedTtfb },
          capturedVault,
        );
      });
    }

    // ── 7b-ii. Normal streaming path (no vault) ──────────────────────────────
    // Note: if two streaming responses overlap and both generate tool_use blocks,
    // ConversationTracker uses last-writer-wins — acceptable since overlapping
    // turns in the same conversation are rare and the conversationId is still correct.
    result.streamMeta?.then(async (meta) => {
      // Response-side content policy (post-hoc) — stream already forwarded;
      // violations are flagged via outcome:'policy-violation' in the event.
      const responseContentResult = await evaluateLlmResponseContent(
        meta.responseText ?? '',
        capturedEvent,
        capturedContentRules,
        capturedCredVault,
      );

      const isViolation = responseContentResult.action !== 'ALLOW';
      if (isViolation) {
        logger.warn(
          { model: capturedEvent.model, rule: responseContentResult.matchedRule, action: responseContentResult.action },
          'Response content policy violation on streaming response (post-hoc — stream already forwarded to client)',
        );
      }

      const finalMeta = isViolation && responseContentResult.redactedText
        ? { ...meta, responseText: responseContentResult.redactedText }
        : meta;

      emitEnrichedEvent(
        isViolation ? { ...capturedEvent, outcome: 'policy-violation' } : capturedEvent,
        finalMeta,
        { statusCode: capturedStatusCode, durationMs: Date.now() - capturedForwardStart, ttfbMs: capturedTtfb },
        capturedVault,
      );
    }).catch((err: unknown) => {
      logger.error({ err, eventId: capturedEvent.id }, 'Failed to emit LLM stream response event');
      bus.emit('llm:response', {
        ...capturedEvent,
        outcome: 'error',
        errorMessage: err instanceof Error ? err.message : 'Stream pipeline error',
        ttfbMs: capturedTtfb,
        totalDurationMs: Date.now() - capturedForwardStart,
      });
    });

    return stream(c, async (s) => {
      const reader = result.stream!.getReader();
      try {
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          await s.write(value);
        }
      } catch {
        // Client disconnected — cancel the upstream so the TransformStream's cancel()
        // handler fires, settling streamMeta with partial: true.
        result.stream!.cancel().catch(() => {});
      } finally {
        reader.releaseLock();
      }
    });
  };
}

// ─── Gateway factory ──────────────────────────────────────────────────────────

export function llmGateway(opts: LlmGatewayOptions): Hono {
  const app = new Hono();
  // One rate limiter + one conversation tracker per gateway instance.
  // Per-instance scope avoids shared state across test suites.
  const llmRateLimiter = new RateLimiter();
  const conversationTracker = new ConversationTracker();

  // ── Health ────────────────────────────────────────────────────────────────
  app.get('/llm/health', (c) =>
    c.json({
      status: 'ok',
      enabled: opts.config.enabled,
      logLevel: opts.config.logLevel,
    }),
  );

  // ── Anthropic ─────────────────────────────────────────────────────────────
  const anthropicHandler = buildProviderHandler(anthropicProvider, opts, llmRateLimiter, conversationTracker);
  app.post('/llm/anthropic/*', anthropicHandler);
  // Some clients send OPTIONS preflight
  app.options('/llm/anthropic/*', (c) => {
    c.header('access-control-allow-methods', 'POST, GET, OPTIONS');
    c.header('access-control-allow-headers', '*');
    return c.body(null, 204);
  });

  // ── OpenAI ────────────────────────────────────────────────────────────────
  const openaiHandler = buildProviderHandler(openaiProvider, opts, llmRateLimiter, conversationTracker);
  app.post('/llm/openai/*', openaiHandler);
  app.options('/llm/openai/*', (c) => {
    c.header('access-control-allow-methods', 'POST, GET, OPTIONS');
    c.header('access-control-allow-headers', '*');
    return c.body(null, 204);
  });

  // ── Logs endpoint ─────────────────────────────────────────────────────────
  // The ring buffer is wired in server.ts; the gateway only references it via
  // an injected accessor to keep this file free of storage concerns.

  return app;
}

// ─── Logs accessor interface ──────────────────────────────────────────────────
// server.ts mounts its own /logs/llm-calls endpoint using the ring buffer directly.
// This keeps the gateway decoupled from storage.
