// Shared types for the Rind MCP proxy — canonical definitions for @rind/core
// All events are structurally compatible with OpenTelemetry spans for future export

// ─── LLM Log verbosity ───────────────────────────────────────────────────────

/**
 * Controls how much of the prompt/response is persisted.
 *
 * - metadata: only model, tokens, cost, latency, threats (default in production)
 * - full:     complete prompts + responses (default in development)
 * - preview:  first 200 chars of system prompt + last user msg + first 200 chars of response
 */
export type LlmLogLevel = 'metadata' | 'full' | 'preview';

// ─── LLM Threat detection ────────────────────────────────────────────────────

export type LlmThreatType =
  | 'PII_LEAK'               // SSN, credit card, phone, email in outbound prompt
  | 'CREDENTIAL_IN_PROMPT'   // API key, private key, password in outbound prompt
  | 'INJECTION_IN_RESPONSE'  // prompt injection patterns in inbound response
  | 'CREDENTIAL_IN_RESPONSE' // credentials in inbound response
  | 'COST_ANOMALY';          // single call exceeds cost threshold

export interface LlmThreat {
  type: LlmThreatType;
  severity: 'critical' | 'high' | 'medium';
  detail: string;
}

// ─── Tool-use correlation ─────────────────────────────────────────────────────

/**
 * A tool_use block generated by an LLM response.
 * Captured from streaming (input_json_delta accumulation) or non-streaming responses.
 * Used to link this LLM call to subsequent LLM calls that consume the tool result.
 */
export interface ToolUseRef {
  /** Anthropic tool_use_id — unique per tool invocation, e.g. "toolu_01abc..." */
  id: string;
  /** Tool name as declared in the request tools array, e.g. "Bash" */
  name: string;
  /** Tool input as generated by the model (may be partial if stream was cancelled) */
  input: unknown;
}

// ─── LLM call event ──────────────────────────────────────────────────────────

/**
 * Emitted once per LLM API call. Initially emitted at request time with outcome
 * 'pending', then enriched and re-emitted as 'llm:response' after the response
 * (or stream) completes.
 *
 * Structurally compatible with OpenTelemetry spans for future export.
 */
export interface LlmCallEvent {
  /** Stable unique ID for this call (randomUUID) */
  id: string;
  /** Session this call belongs to — correlated via API key hash or x-rind-session header */
  sessionId: string;
  /** Agent identity */
  agentId: string;
  /** LLM provider */
  provider: 'anthropic' | 'openai' | 'google';
  /** Model name as sent by the client — e.g. "claude-sonnet-4-20250514" */
  model: string;
  /** Unix ms timestamp of request arrival */
  timestamp: number;

  // ── Request metadata ───────────────────────────────────────────────────────
  /** Number of messages in the conversation */
  messageCount: number;
  /** Character count of the system prompt */
  systemPromptLength: number;
  /** Whether the request uses streaming */
  streaming: boolean;

  // ── Content (conditional on logLevel) ─────────────────────────────────────
  // These fields are undefined when logLevel is 'metadata'.
  // When logLevel is 'preview', they contain truncated versions.
  // Never capture API keys — they are stripped before any content is stored.
  /** Full messages array (logLevel: full) or truncated (logLevel: preview) */
  messages?: unknown;
  /** Full response text (logLevel: full) or truncated (logLevel: preview) */
  responseText?: string;

  // ── Usage (backfilled from response) ──────────────────────────────────────
  inputTokens?: number;
  outputTokens?: number;
  estimatedCostUsd?: number;

  // ── Latency ───────────────────────────────────────────────────────────────
  /** Time from request send to first SSE chunk (streaming only) */
  ttfbMs?: number;
  /** Time from request send to stream end / response received */
  totalDurationMs?: number;

  // ── Scanning ──────────────────────────────────────────────────────────────
  requestThreats?: LlmThreat[];
  responseThreats?: LlmThreat[];
  /** Content inspection audit — populated when content-based policy rules ran */
  contentInspection?: ContentInspectionAudit;

  // ── Outcome ───────────────────────────────────────────────────────────────
  outcome: 'forwarded' | 'blocked' | 'error';
  statusCode?: number;
  errorMessage?: string;

  // ── Policy ────────────────────────────────────────────────────────────────
  matchedRule?: string;

  // ── Conversation threading (tool_use_id chain) ────────────────────────────
  /**
   * tool_use blocks generated by this LLM response.
   * Populated after stream/response completes. Used to link this call to subsequent
   * calls that contain matching tool_result blocks.
   */
  toolUses?: ToolUseRef[];
  /**
   * tool_use_ids referenced in this request's tool_result blocks.
   * Present when this call is a continuation of a previous turn.
   */
  referencedToolUseIds?: string[];
  /**
   * ID of the LlmCallEvent that generated the tool_use blocks this request consumes.
   * Null/absent for the first call in a conversation.
   */
  parentLlmCallId?: string;
  /**
   * Stable ID for the full conversation thread.
   * Equals the root LlmCallEvent.id for all calls in the same conversation.
   */
  conversationId?: string;
}

// ─── LLM Proxy config ─────────────────────────────────────────────────────────

/**
 * LLM proxy configuration — part of ProxyConfig.llmProxy.
 *
 * Defaults: enabled=false, logLevel derived from NODE_ENV,
 * upstream URLs are the real provider endpoints.
 */
export interface LlmProxyConfig {
  /** Feature flag — if false, /llm/* routes are never mounted */
  enabled: boolean;
  /** How much content to persist in logs */
  logLevel: LlmLogLevel;
  /** Upstream Anthropic API base URL (default: https://api.anthropic.com) */
  anthropicUpstream: string;
  /** Upstream OpenAI API base URL (default: https://api.openai.com) */
  openaiUpstream: string;
  /** Upstream Google AI base URL (default: https://generativelanguage.googleapis.com) */
  googleUpstream: string;
  /**
   * Emit 'llm:cost-anomaly' when a single call exceeds this USD threshold.
   * undefined = disabled (default).
   */
  costAnomalyThresholdUsd?: number;
  /**
   * Max LLM calls per agent per minute. undefined = no rate limiting (default).
   */
  rateLimitPerAgentPerMinute?: number;
}

/**
 * Returns the default LlmProxyConfig.
 * logLevel defaults to 'full' in development, 'metadata' in production.
 */
export function defaultLlmProxyConfig(env?: string): LlmProxyConfig {
  return {
    enabled: process.env['RIND_LLM_PROXY'] !== 'false',
    logLevel: (env ?? process.env['NODE_ENV']) !== 'production' ? 'full' : 'metadata',
    anthropicUpstream: 'https://api.anthropic.com',
    openaiUpstream: 'https://api.openai.com',
    googleUpstream: 'https://generativelanguage.googleapis.com',
  };
}

// ─── Policy action ───────────────────────────────────────────────────────────

export type PolicyAction =
  | 'ALLOW'
  | 'DENY'
  | 'REQUIRE_APPROVAL'
  | 'RATE_LIMIT'
  | 'REDACT'        // replace matched content with [REDACTED], pass through
  | 'PSEUDONYMIZE'; // replace with vault token, rehydrate after LLM responds

// ─── Tool call events ────────────────────────────────────────────────────────

export interface ToolCallEvent {
  sessionId: string;
  sessionName?: string; // Human-readable name from Claude Code /rename
  agentId: string; // identity-aware from day 1
  serverId: string;
  toolName: string;
  input: unknown;
  timestamp: number;
  // Enriched after policy evaluation — not present on the initial event
  outcome?: 'allowed' | 'blocked' | 'require-approval' | 'approved' | 'disapproved' | 'approval-timeout' | 'upstream-error' | 'upstream-timeout';
  reason?: string;
  // Name of the policy rule that matched (if any)
  matchedRule?: string;
  // Which engine produced the matched rule — 'policy' for the policy engine, 'scan' for the scanner
  matchedRuleType?: 'policy' | 'scan';
  // Source classification: 'builtin' for Claude Code tools, 'mcp' for MCP server tools
  source?: 'builtin' | 'mcp' | 'proxy';
  // Human-readable label: "Bash: git status", "Read: server.ts", "Edit: types.ts"
  toolLabel?: string;
  // Working directory where the agent is operating
  cwd?: string;
  // Deterministic correlation ID linking PreToolUse → PostToolUse for the same call
  correlationId?: string;
  // PostToolUse response data — enriched server-side when PostToolUse arrives
  response?: {
    outputPreview?: string;
    outputTruncated?: boolean;
    outputSizeBytes?: number;
    outputHash?: string;
    threats?: ResponseThreat[];
    timestamp: number;
  };
}

export interface ToolResponseEvent {
  sessionId: string;
  agentId: string;
  serverId: string;
  toolName: string;
  output: unknown;
  durationMs: number;
  threats: ResponseThreat[]; // prompt injection, credential patterns
}

export interface ToolErrorEvent {
  sessionId: string;
  serverId: string;
  agentId: string;
  toolName: string;
  /** 'upstream-unreachable' = ECONNREFUSED / fetch failed; 'upstream-timeout' = AbortError */
  errorKind: 'upstream-unreachable' | 'upstream-timeout';
  durationMs: number;
}

// ─── Response-side threat detection ─────────────────────────────────────────

export interface ResponseThreat {
  type: 'PROMPT_INJECTION' | 'CREDENTIAL_LEAK' | 'SUSPICIOUS_REDIRECT' | 'INDIRECT_PROMPT_INJECTION';
  severity: 'critical' | 'high' | 'medium';
  pattern: string;
  sanitized: boolean;
}

// ─── Schema + scan ───────────────────────────────────────────────────────────

export interface ToolDefinition {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}

export interface ServerSchema {
  serverId: string;
  hash: string; // SHA-256 of sorted tool definitions
  tools: ToolDefinition[];
  scannedAt: number;
  findings: ScanFinding[];
}

export type ScanFindingSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';
export type ScanFindingCategory =
  | 'AUTH_MISSING'
  | 'TOOL_POISONING'
  | 'OVER_PERMISSIONED'
  | 'SCHEMA_DRIFT'
  | 'SCHEMA_DRIFT_TOOL_ADDED'
  | 'SCHEMA_DRIFT_TOOL_MODIFIED'
  | 'SCHEMA_DRIFT_TOOL_REMOVED'
  | 'CROSS_SERVER_SHADOWING';

export interface ScanFinding {
  category: ScanFindingCategory;
  severity: ScanFindingSeverity;
  toolName?: string;
  detail: string;
}

export interface ScanResult {
  serverId: string;
  scannedAt: number;
  findings: ScanFinding[];
  passed: boolean; // true = no critical/high findings
}

// ─── Session ─────────────────────────────────────────────────────────────────

export interface Session {
  sessionId: string;
  agentId: string;
  startedAt: number;
  active: boolean; // false = killed via kill-switch
  toolCallCount: number;
  estimatedCostUsd: number;
}

// ─── Policy — parameter matching (D-016) ─────────────────────────────────────

/** Conditions to match against a tool input parameter value (recursive key lookup, depth ≤ 5). */
export interface ParameterMatcher {
  contains?: string[]; // all substrings must be present (case-insensitive)
  regex?: string; // full-match regex (pre-compiled at policy load time)
  startsWith?: string;
  gt?: number;
  lt?: number;
  gte?: number;
  lte?: number;
  eq?: unknown;
  in?: unknown[];
}

// ─── Loop detection (policy-driven) ──────────────────────────────────────────

/** Loop detection condition on a policy rule. The rule's action fires only when
 *  the loop condition is met AND the rule's match criteria apply. */
export interface LoopCondition {
  /** Detection type:
   *  - exact: same tool + same input hash repeated
   *  - consecutive: same tool name called in a row (any input)
   *  - subcommand: same extracted sub-command repeated (Bash only) */
  type: 'exact' | 'consecutive' | 'subcommand';
  /** Number of occurrences that trigger the loop (e.g. 5 = block on 5th repeat) */
  threshold: number;
  /** Sliding window size — how many recent calls to consider (default 30) */
  window?: number;
}

// ─── LLM content detection ───────────────────────────────────────────────────

/**
 * Shared detection strategy mixin — all detector configs extend this.
 * Defines the pipeline of detection stages to run in order.
 * Phase 1: only 'regex' is implemented. 'ml_ner' and 'llm_judge' are
 * forward-compatible stubs that fail open and log a warning.
 */
export interface DetectionStrategy {
  /**
   * Ordered pipeline of detection stages.
   * Each stage runs only if the previous stage confidence < advanceThreshold.
   * Default: ['regex']
   */
  pipeline?: ('regex' | 'ml_ner' | 'llm_judge')[];
  /**
   * Confidence threshold below which the next pipeline stage is invoked.
   * Default: 0.7
   */
  advanceThreshold?: number;
  /** Config for llm_judge stage — required if pipeline includes 'llm_judge' */
  llmJudge?: {
    model?: string;         // defaults to proxy's own LLM config
    threshold?: number;     // confidence required to trigger action, default 0.85
    timeoutMs?: number;     // default 5000
    failMode?: 'open' | 'closed'; // on timeout: open = skip stage, closed = block; default 'open'
  };
  /** Config for ml_ner stage — required if pipeline includes 'ml_ner' */
  mlModel?: {
    endpoint?: string;      // HTTP inference endpoint
    modelId?: string;       // local model identifier
    timeoutMs?: number;
    failMode?: 'open' | 'closed'; // default 'open'
  };
}

/** Result returned by each detector stage */
export interface DetectionResult {
  triggered: boolean;
  confidence: number;       // 0–1
  stage: 'regex' | 'ml_ner' | 'llm_judge';
  matchedPattern?: string;  // pattern name or regex string that matched
  entityType?: string;      // for PII detections
}

/** Which LLM content detectors can be configured on a rule */
export type LlmDetector = 'pii' | 'secret' | 'prompt_injection' | 'dlp';

/** Specifies which part of the LLM conversation to inspect */
export interface LlmContentMatch {
  /** Which direction to inspect */
  scope: 'request' | 'response' | 'both';
  /** Which message roles to scan (default: all roles) */
  targets?: ('system' | 'user' | 'assistant')[];
  /** Which detector types to run */
  detectors: LlmDetector[];
}

/** PII entity types recognised by the PII detector */
export type PiiEntity =
  | 'EMAIL'
  | 'PHONE'
  | 'SIN'           // Canada Social Insurance Number
  | 'SSN'           // US Social Security Number
  | 'CREDIT_CARD'
  | 'IBAN'
  | 'PASSPORT'
  | 'PERSON_NAME'
  | 'ADDRESS'
  | 'IP_ADDRESS'
  | 'DATE_OF_BIRTH'
  | 'HEALTH_CARD';

/** Config for the 'pii' detector — used when match.content.detectors includes 'pii' */
export interface PiiDetectorConfig extends DetectionStrategy {
  entities: PiiEntity[];
  locale?: string;              // e.g. 'en-CA' — affects SIN vs SSN, postal format
  confidenceThreshold?: number; // 0–1, default 0.7
}

/** Built-in secret pattern names */
export type BuiltinSecretPattern =
  | 'openai_key'
  | 'anthropic_key'
  | 'aws_access_key'
  | 'github_token'
  | 'stripe_key'
  | 'jwt'
  | 'private_key'
  | 'bearer_token'
  | 'generic_api_key';

/** Config for the 'secret' detector */
export interface SecretDetectorConfig extends DetectionStrategy {
  /** Which built-in patterns to run. If omitted, all built-in patterns apply. */
  patterns?: BuiltinSecretPattern[];
  /** Additional custom regex patterns */
  custom?: { name: string; regex: string }[];
}

/** Config for the 'prompt_injection' detector */
export interface InjectionDetectorConfig extends DetectionStrategy {}

/** Config for the 'dlp' detector — user-defined data loss prevention patterns */
export interface DlpDetectorConfig extends DetectionStrategy {
  patterns: { name: string; regex: string; severity: 'critical' | 'high' | 'medium' }[];
}

// ─── Content inspection audit types (no PII values) ──────────────────────────

/** A single detection match — safe for the main audit log (no original values) */
export interface DetectorMatchAudit {
  /** Token or pattern name: "EMAIL_1", "openai_key", "role_override_attempt" */
  label: string;
  /** Entity or pattern type: "EMAIL", "openai_key", "PROMPT_INJECTION" */
  type: string;
  confidence: number;
  stage: 'regex' | 'ml_ner' | 'llm_judge';
}

/** Per-detector summary for one content inspection pass */
export interface DetectorAuditResult {
  detector: LlmDetector;
  decidedBy: 'regex' | 'ml_ner' | 'llm_judge';
  matchCount: number;
  maxConfidence: number;
  action: PolicyAction;
  durationMs: number;
  /** Safe for audit log — contains no original PII values */
  matches: DetectorMatchAudit[];
}

/**
 * PII pseudonymization stats — safe for production audit log.
 * No original values. Hash is salted per-request (non-reversible).
 */
export interface PIIAuditStats {
  tokenCount: number;
  entityTypeBreakdown: Record<string, number>; // { EMAIL: 2, PHONE: 1 }
  /**
   * Salted hashes for deduplication (Tier 2).
   * Hash = sha256(requestId + entityType + originalValue) — request-scoped, non-reversible.
   */
  valueHashes?: { hash: string; entityType: PiiEntity; occurrences: number }[];
  rehydrated: boolean;
}

/** Content inspection summary attached to LlmCallEvent — no PII values */
export interface ContentInspectionAudit {
  detectorsRan: LlmDetector[];
  results: DetectorAuditResult[];
  inspectionDurationMs: number;
  pseudonymization?: PIIAuditStats;
}

// ─── Policy ──────────────────────────────────────────────────────────────────

export interface PolicyRule {
  name: string;
  agent: string; // '*' = all agents
  enabled?: boolean; // default true — set to false to disable without deleting
  match: {
    tool?: string[];
    toolPattern?: string; // glob pattern e.g. "billing.*"
    timeWindow?: {
      daysOfWeek?: number[]; // 0=Sun, 1=Mon...6=Sat
      hours?: string; // "09:00-18:00" UTC
    };
    // D-016: input parameter matching — recursive key lookup in tool input
    parameters?: Record<string, ParameterMatcher>;
    // Sub-command matching (Bash only) — extracts sub-commands (e.g. "git push")
    // and matches if ANY extracted sub-command is in this list (case-insensitive).
    // "git status && npm publish" with subcommand: ['npm publish'] → matches.
    subcommand?: string[];
    // LLM API proxy matching (D-041 scope clarification)
    // Glob patterns for model names: ["claude-sonnet-*", "gpt-4o"]
    llmModel?: string[];
    // Provider names: ["anthropic", "openai", "google"]
    llmProvider?: string[];
    // LLM content-based matching — inspects prompt/response body.
    // When set, the rule runs through the content detection pipeline
    // instead of (or in addition to) metadata matching.
    content?: LlmContentMatch;
  };
  action: PolicyAction;
  // D-013: REQUIRE_APPROVAL metadata (parsed but async flow is Phase 2)
  approval?: {
    timeout?: string; // e.g. "30m" — informational in Phase 1
    onTimeout?: 'DENY' | 'ALLOW'; // informational in Phase 1
  };
  // D-014: cost tracking
  costEstimate?: number; // USD per call charged to session when this rule matches
  limits?: {
    maxCallsPerSession?: number;
    maxCallsPerHour?: number;
    maxCostPerSession?: number;
    maxCostPerHour?: number;
  };
  // D-017: rate limiting (used when action === 'RATE_LIMIT')
  rateLimit?: {
    limit: number;
    window: string; // "1m" | "1h" | "1d" | etc.
    scope: 'per_agent' | 'per_tool' | 'global';
  };
  // D-022: error handling fail mode
  failMode?: 'closed' | 'open'; // default 'closed': if evaluation throws, DENY
  // D-036: evaluation priority — lower number = evaluated first (default 50 for custom, 100 for packs)
  priority?: number;
  // Policy-driven loop detection — rule's action fires only when the loop condition is met
  loop?: LoopCondition;
  // ── LLM content detector configs ──────────────────────────────────────────
  // Only relevant when match.content is set. Each field configures the
  // corresponding detector listed in match.content.detectors.
  pii?: PiiDetectorConfig;
  secrets?: SecretDetectorConfig;
  injection?: InjectionDetectorConfig;
  dlp?: DlpDetectorConfig;
}

export interface PolicyConfig {
  policies: PolicyRule[];
}

// ─── Policy packs (D-036) ─────────────────────────────────────────────────────

/** Tracks which authoring path created or last modified a rule. */
export type PolicyRuleSource = 'manual' | 'yaml' | `pack:${string}` | 'ai-assisted';

export interface PolicyRuleMeta {
  source: PolicyRuleSource;
  createdAt: string; // ISO 8601
  modifiedFromPack?: boolean; // true if user customized a rule that originated from a pack
}

/** A PolicyRule augmented with authoring metadata (used by the API layer, stripped before engine eval). */
export interface PolicyRuleWithMeta extends PolicyRule {
  _meta?: PolicyRuleMeta;
}

/** Describes a field in a pack that the user can customize without editing raw YAML. */
export interface PackCustomization {
  ruleIndex: number; // index into PolicyPack.rules
  field: string; // dot-path to the field, e.g. "rateLimit.limit"
  label: string; // human-readable: "Max calls per minute"
  type: 'number' | 'string' | 'enum' | 'boolean';
  options?: string[]; // for enum type
  default: unknown;
}

export type PackCategory =
  | 'data-protection'
  | 'infrastructure'
  | 'compliance'
  | 'communication'
  | 'llm-safety'; // prompt injection, PII-in-prompt, secret scanning
export type PackSeverity = 'strict' | 'moderate' | 'permissive';

export interface PolicyPack {
  id: string; // e.g. "sql-protection"
  version: string; // semver, e.g. "1.0.0"
  name: string; // "SQL Protection"
  description: string; // one-sentence summary
  category: PackCategory;
  tags: string[];
  severity: PackSeverity;
  rules: PolicyRule[];
  customizable: PackCustomization[];
  // Tool name prefixes that suggest this pack is relevant (for smart defaults)
  requiredTools?: string[];
}

/** Tracks which packs are enabled and their per-instance customizations. */
export interface PackState {
  packId: string;
  enabled: boolean;
  enabledAt?: string; // ISO 8601
  customizations?: Record<string, unknown>; // field path → value overrides
}

/** Extended PolicyConfig that tracks pack state alongside rules. */
export interface PolicyConfigV2 {
  policies: PolicyRuleWithMeta[];
  enabledPacks: PackState[];
}

// ─── Audit trail (D-020) ─────────────────────────────────────────────────────

/** Every policy decision produces an AuditEntry written to the JSONL audit log. */
export interface AuditEntry {
  timestamp: string; // ISO 8601
  eventType:
    | 'tool:call'
    | 'tool:blocked'
    | 'tool:response'
    | 'tool:threat'
    | 'tool:error'
    | 'scan:complete'
    | 'session:created'
    | 'session:killed'
    | 'policy:mutation'
    | 'llm:request'
    | 'llm:response'
    | 'llm:blocked'
    | 'llm:error';
  sessionId: string;
  agentId: string;
  serverId: string;
  action: string; // ALLOW, DENY, BLOCKED_*, etc.
  policyRule?: string; // name of matching rule, or undefined for default-allow
  toolName?: string;
  reason?: string;
  threats?: ResponseThreat[];
  input?: unknown; // always included (needed for security investigation)
  output?: unknown; // only included when auditIncludeOutput is true
}
